API_HOST_URL: 'https://verde.cursos.aprende.gob.mx'
SSO_URL: 'https://verde.cursos.aprende.gob.mx'
SSO_FINISHED_URL:  'https://verde.cursos.aprende.gob.mx'
ENVIRONMENT_DISPLAY_NAME: 'Verde'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
OAUTH_CLIENT_ID: '83xvTzfuCKAlCwr0kYdCXAxdyXHJIvg7jJXOZioY'

SSO_BUTTON_TITLE:
    ar: "الدخول عبر SSO"
    en: "Sign in with SSO"

EXPERIMENTAL_FEATURES:
    APP_LEVEL_DOWNLOADS:
        ENABLED: false

UI_COMPONENTS:
    COURSE_UNIT_PROGRESS_ENABLED: false
    COURSE_NESTED_LIST_ENABLED: false
    LOGIN_REGISTRATION_ENABLED: true
    SAML_SSO_LOGIN_ENABLED: false
    SAML_SSO_DEFAULT_LOGIN_BUTTON: false
